[package]
name = "qckprism"
version = "0.1.0"
authors = ["zapp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.6.4"
byteorder = "1.3.4"
clap = "2.33.3"
hex = "0.4.2"
